"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = ["<Esc>"]
run = "escape"
desc = "Exit visual mode, clear selected, or cancel search"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin bypass --args=smart_enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin bypass --args=smart_enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = ["T"]
run = "plugin --sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = ["i"]
run = "plugin searchjump"
desc = "searchjump mode"

[[manager.prepend_keymap]]
on = ["i"]
run = "plugin searchjump --args='autocd'"
desc = "searchjump mode(auto cd select folder)"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["<C-n>"]
run = '''
	shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''

[[manager.prepend_keymap]]
on = ["f"]
run = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on = ["F"]
run = "plugin smart-filter"
desc = "Smart filter"
