# https://alacritty.org/config-alacritty.html
import = ["/usr/share/alacritty/themes/catppuccin_macchiato.toml"]

[shell]
program = "/bin/fish"
args = ["-l"]

[window]
opacity = 0.8
blur = true
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
size = 11
normal = { family = "monospace", style = "bold" }

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"
